[package]
name = "tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.53.0"
image = "0.24.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

